[package]
name = "ucentral-cgw"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
env_logger = "0.5.0"
log = "0.4.20"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = { version = "*", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"] }
tokio-native-tls = "*"
tokio-rustls = "*"
tokio-postgres = { version = "0.7.10", features = ["with-eui48-1"]}
tokio-pg-mapper = "0.2.0"
tungstenite = { version = "*"}
mio = "0.6.10"
native-tls = "*"
futures-util = { version = "0.3.0", default-features = false }
futures-channel = "0.3.0"
futures-executor = { version = "0.3.0", optional = true }
futures = "0.3.0"
rlimit = "0.10.1"
tonic = "0.10.2"
prost = "0.12"
rdkafka = "0.35.0"
clap = { version = "4.4.8", features = ["derive"] }
eui48 = "1.1.0"
uuid = { version = "1.6.1", features = ["serde"] }
redis-async = "0.16.1"

[build-dependencies]
tonic-build = "0.10"
prost-build = "0.12"
