apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-citus.yml -c -o patroni-compose
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: clickhouse-01
  name: clickhouse-01
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: clickhouse-01
