apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-citus.yml -c -o patroni-compose
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: clickhouse-02
  name: clickhouse-02
spec:
  ports:
    - name: "8124"
      port: 8124
      targetPort: 8123
    - name: "9001"
      port: 9001
      targetPort: 9000
  selector:
    io.kompose.service: clickhouse-02
