apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-citus.yml -c -o patroni-compose
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: clickhouse-03
  name: clickhouse-03
spec:
  ports:
    - name: "8125"
      port: 8125
      targetPort: 8123
    - name: "9002"
      port: 9002
      targetPort: 9000
  selector:
    io.kompose.service: clickhouse-03
