apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-citus.yml -c -o patroni-compose
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: haproxy
