apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-citus.yml -c -o patroni-compose
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: work1-2
  name: work1-2
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: work1-2
